[meta]
letter = "B"
objective = "To determine the applicant exhibits satisfactory knowledge, risk management, and skills associated with obtaining, understanding, and applying weather information for a flight under IFR."
name = "Weather Information"
references = [
    "14 CFR part 91",
    "FAA-H-8083-25",
    "AC 00-6",
    "AC 00-45",
    "AIM",
]

[meta.section]
name = "Preflight Preparation"
numeral = "I"

[knowledge]
1 = "Sources of weather data (e.g., National Weather Service, Flight Service) for flight planning purposes."
2 = "Acceptable weather products and resources utilized for preflight planning, current and forecast weather for departure and en route operations and arrival phases of flight."
3 = "Meteorology applicable to the departure, en route, alternate, and destination for flights conducted under Instrument Flight Rules (IFR) to include expected climate and hazardous conditions such as:"
3a = "a. Atmospheric composition and stability"
3b = "b. Wind (e.g., crosswind, tailwind, windshear, mountain wave, etc.)"
3c = "c. Temperature"
3d = "d. Moisture/precipitation"
3e = "e. Weather system formation, including air masses and fronts"
3f = "f. Clouds"
3g = "g. Turbulence"
3h = "h. Thunderstorms and microbursts"
3i = "i. Icing and freezing level information"
3j = "j. Fog/mist"
3k = "k. Frost"
3l = "l. Obstructions to visibility (e.g., smoke, haze, volcanic ash, etc.)"
4 = "Flight deck displays of digital weather and aeronautical information."

[risk_management]
1 = "Factors involved in making the go/no-go and continue/divert decisions, to include:"
1a = "a. Circumstances that would make diversion prudent"
1b = "b. Personal Weather Minimums"
1c = "c. Hazardous weather conditions to include known or forecast icing or turbulence aloft"
2 = "Limitations of:"
2a = "a. Onboard weather equipment"
2b = "b. Aviation weather reports and forecasts"
2c = "c. Inflight weather resources"

[skills]
1 = "Use available aviation weather resources to obtain an adequate weather briefing."
2 = "Analyze the implications of at least three of the conditions listed in K3a through K3l above, using actual weather or weather conditions in a scenario provided by the evaluator."
3 = "Correlate weather information to make a competent go/no-go decision."
4 = "Determine whether an alternate airport is required, and, if required, whether the selected alternate airport meets regulatory requirements."
