[meta]
letter = "B"
objective = "To determine the applicant exhibits satisfactory knowledge, risk management, and skills associated with obtaining, understanding, and applying weather information for a flight under IFR."
name = "Weather Information"
references = [
    "14 CFR part 91",
    "FAA-H-8083-25",
    "AC 00-6",
    "AC 00-45",
    "AIM",
]

[knowledge]
k1 = "Sources of weather data (e.g., National Weather Service, Flight Service) for flight planning purposes."
k2 = "Acceptable weather products and resources utilized for preflight planning, current and forecast weather for departure and en route operations and arrival phases of flight."
k3 = "Meteorology applicable to the departure, en route, alternate, and destination for flights conducted under Instrument Flight Rules (IFR) to include expected climate and hazardous conditions such as:"
k3a = "a. Atmospheric composition and stability"
k3b = "b. Wind (e.g., crosswind, tailwind, windshear, mountain wave, etc.)"
k3c = "c. Temperature"
k3d = "d. Moisture/precipitation"
k3e = "e. Weather system formation, including air masses and fronts"
k3f = "f. Clouds"
k3g = "g. Turbulence"
k3h = "h. Thunderstorms and microbursts"
k3i = "i. Icing and freezing level information"
k3j = "j. Fog/mist"
k3k = "k. Frost"
k3l = "l. Obstructions to visibility (e.g., smoke, haze, volcanic ash, etc.)"
k4 = "Flight deck displays of digital weather and aeronautical information."

[risk_management]
r1 = "Factors involved in making the go/no-go and continue/divert decisions, to include:"
r1a = "a. Circumstances that would make diversion prudent"
r1b = "b. Personal Weather Minimums"
r1c = "c. Hazardous weather conditions to include known or forecast icing or turbulence aloft"
r2 = "Limitations of:"
r2a = "a. Onboard weather equipment"
r2b = "b. Aviation weather reports and forecasts"
r2c = "c. Inflight weather resources"

[skills]
s1 = "Use available aviation weather resources to obtain an adequate weather briefing."
s2 = "Analyze the implications of at least three of the conditions listed in K3a through K3l above, using actual weather or weather conditions in a scenario provided by the evaluator."
s3 = "Correlate weather information to make a competent go/no-go decision."
s4 = "Determine whether an alternate airport is required, and, if required, whether the selected alternate airport meets regulatory requirements."
