[meta]
letter = "A"
objective = "To determine the applicant exhibits satisfactory knowledge, risk management, and skills associated with performing basic instrument flight maneuvers solely by reference to instruments."
name = "Instrument Flight"
references = [
    "14 CFR part 61",
    "FAA-8083-2",
    "FAA-H-8083-15",
]

[knowledge]
k1 = "Elements related to attitude instrument flying during straight-and-level flight, climbs, turns, and descents while conducting various instrument flight procedures."
k2 = "Interpretation, operation, and limitations of pitch, bank, and power instruments."
k3 = "Normal and abnormal instrument indications and operations."

[risk_management]
r1 = "Situations that can affect physiology and degrade instrument cross-check."
r2 = "Spatial disorientation and optical illusions."
r3 = "Flying unfamiliar airplanes, or operating with unfamiliar flight display systems and avionics."

[skills]
s1 = "Maintain altitude ±100 feet during level flight, selected headings ±10°, airspeed ±10 knots, and bank angles ±5° during turns."
s2 = "Use proper instrument cross-check and interpretation, and apply the appropriate pitch, bank, power, and trim corrections when applicable."
