[meta]
letter = "B"
objective = "To determine the applicant exhibits satisfactory knowledge, risk management, and skills associated with recovering from unusual flight attitudes solely by reference to instruments."
name = "Recovery from Unusual Flight Attitudes"
references = [
    "14 CFR part 61",
    "FAA-H-8083-15",
]

[knowledge]
k1 = "Procedures for recovery from unusual flight attitudes."
k2 = "Unusual flight attitude causal factors, including physiological factors, system and equipment failures, and environmental factors."

[risk_management]
r1 = "Situations that could lead to loss of control or unusual flight attitudes (e.g., stress, task saturation, and distractions)."
r2 = "Failure to recognize an unusual flight attitude and follow the proper recovery procedure."
r3 = "Exceeding the operating envelope during the recovery."

[skills]
s1 = "Use proper instrument cross-check and interpretation to identify an unusual attitude (including both nose-high and nose-low), and apply the appropriate pitch, bank, and power corrections, in the correct sequence, to return to a stabilized level flight attitude."
