[meta]
letter = "B"
objective = "To determine the applicant exhibits satisfactory knowledge, risk management, and skills associated with holding procedures solely by reference to instruments."
name = "Holding Procedures"
references = [
    "14 CFR parts 61",
    "91",
    "FAA-H-8083-15",
    "FAA-H-8083-16",
    "AIM",
]

[meta.section]
name = "Air Traffic Control Clearances and Procedures"
numeral = "III"

[knowledge]
1 = "Elements related to holding procedures, including reporting criteria, appropriate speeds, and recommended entry procedures for standard, nonstandard, published, and nonpublished holding patterns."

[risk_management]
1 = "Recalculating fuel reserves if assigned an unanticipated EFC time."
2 = "Scenarios and circumstances that could result in minimum fuel or the need to declare an emergency."
3 = "Scenarios that could lead to holding, including deteriorating weather at the planned destination."
4 = "Improper holding entry and improper wind correction while holding."

[skills]
1 = "Explain and use an entry procedure that ensures the airplane remains within the holding pattern airspace for a standard, nonstandard, published, or non-published holding pattern."
2 = "Change to the holding airspeed appropriate for the altitude or airplane when 3 minutes or less from, but prior to arriving at, the holding fix and set appropriate power as needed for fuel conservation."
3 = "Recognize arrival at the holding fix and promptly initiate entry into the holding pattern."
4 = "Maintain airspeed ±10 knots, altitude ±100 feet, selected headings within ±10°, and track a selected course, radial, or bearing within ¾-scale deflection of the CDI."
5 = "Use proper wind correction procedures to maintain the desired pattern and to arrive over the fix as close as possible to a specified time and maintain pattern leg lengths when specified."
6 = "Use an MFD and other graphical navigation displays, if installed, to monitor position in relation to the desired flightpath during holding."
7 = "Comply with ATC reporting requirements and restrictions associated with the holding pattern."
8 = "Demonstrate SRM"
