[meta]
references = [
    "14 CFR parts 61",
    "91",
    "FAA-H-8083-15",
    "AIM",
]
objective = "To determine the applicant exhibits satisfactory knowledge, risk management, and skills associated with ATC clearances and procedures solely by reference to instruments."

[knowledge]
k1 = "Elements and procedures related to ATC clearances and pilot/controller responsibilities for departure, en route, and arrival phases of flight including clearance void times."
k2 = "PIC emergency authority."
k3 = "Lost communication procedures and procedures for flights outside of radar environments."

[risk_management]
r1 = "Failure to fully understand an ATC clearance."
r2 = "Inappropriate, incomplete, or incorrect ATC clearances."
r3 = "ATC clearance inconsistent with airplane performance or navigation capability."
r4 = "ATC clearance intended for other aircraft with similar call signs."

[skills]
s1 = "Correctly copy, read back, interpret, and comply with simulated or actual ATC clearances in a timely manner using standard phraseology as provided in the Aeronautical Information Manual."
s2 = "Correctly set communication frequencies, navigation systems (identifying when appropriate), and transponder codes in compliance with the ATC clearance."
s3 = "Use the current and appropriate paper or electronic navigation publications."
s4 = "Intercept all courses, radials, and bearings appropriate to the procedure, route, or clearance in a timely manner."
s5 = "Maintain the applicable airspeed ±10 knots, headings ±10°, altitude ±100 feet; and track a course, radial, or bearing within ¾-scale deflection of the CDI."
s6 = "Demonstrate SRM."
s7 = "Perform the appropriate airplane checklist items relative to the phase of flight."
