[meta]
letter = "B"
objective = "To determine the applicant exhibits satisfactory knowledge, risk management, and skills associated with managing instruments appropriate for an IFR flight."
name = "Airplane Flight Instruments and Navigation Equipment"
references = [
    "14 CFR parts 61",
    "91",
    "FAA-H-8083-15",
    "AIM",
]

[meta.section]
name = "Preflight Procedures"
numeral = "II"

[knowledge]
1 = "Operation of their airplane’s applicable flight instrument system(s) including:"
1a = "a. Pitot-static instrument system: altimeter, airspeed indicator, vertical speed indicator"
1b = "b. Gyroscopic/electric/vacuum instrument system: attitude indicator, heading indicator, turn-and-slip indicator/turn coordinator"
1c = "c. Electrical systems, electronic flight instrument displays (PFD, MFD), transponder, and ADS-B"
1d = "d. Magnetic compass"
2 = "Operation of their airplane’s applicable navigation system(s) including:"
2a = "a. VOR, DME, ILS, marker beacon receiver/indicators"
2b = "b. RNAV, GPS, Wide Area Augmentation System (WAAS), FMS, autopilot"

[risk_management]
1 = "Failure to monitor and manage automated systems."
2 = "The difference between approved and non-approved navigation devices."
3 = "Common failure modes of flight and navigation instruments."
4 = "The limitations of electronic flight bags."
5 = "Failure to ensure currency of navigation databases."

[skills]
1 = "Operate and manage installed instruments and navigation equipment."
