[meta]
letter = "C"
objective = "To determine the applicant exhibits satisfactory knowledge, risk management, and skills associated with conducting a preflight check on the airplane’s instruments necessary for an IFR flight."
name = "Instrument Flight Deck Check"
references = [
    "14 CFR part 91",
    "FAA-8083-2",
    "FAA-H-8083-3",
    "FAA-H-8083-15",
    "FAA-H-8083-25",
    "AC 91.21-1",
    "POH/AFM",
]

[knowledge]
1 = "Purpose of performing an instrument flight deck check and how to detect possible defects."
2 = "IFR airworthiness, to include airplane inspection requirements and required equipment for IFR flight."
3 = "Required procedures, documentation, and limitations of flying with inoperative equipment."

[risk_management]
1 = "Operating with inoperative equipment."
2 = "Operating with outdated navigation publications or databases."

[skills]
1 = "Perform preflight inspection by following the checklist appropriate to the airplane and determine that the airplane is in a condition for safe instrument flight."
