[meta]
letter = "B"
objective = "To determine the applicant exhibits satisfactory knowledge, risk management, and skills associated with managing instruments appropriate for an IFR flight."
name = "Airplane Flight Instruments and Navigation Equipment"
references = [
    "14 CFR parts 61",
    "91",
    "FAA-H-8083-15",
    "AIM",
]

[knowledge]
k1 = "Operation of their airplane’s applicable flight instrument system(s) including:"
k1a = "a. Pitot-static instrument system: altimeter, airspeed indicator, vertical speed indicator"
k1b = "b. Gyroscopic/electric/vacuum instrument system: attitude indicator, heading indicator, turn-and-slip indicator/turn coordinator"
k1c = "c. Electrical systems, electronic flight instrument displays (PFD, MFD), transponder, and ADS-B"
k1d = "d. Magnetic compass"
k2 = "Operation of their airplane’s applicable navigation system(s) including:"
k2a = "a. VOR, DME, ILS, marker beacon receiver/indicators"
k2b = "b. RNAV, GPS, Wide Area Augmentation System (WAAS), FMS, autopilot"

[risk_management]
r1 = "Failure to monitor and manage automated systems."
r2 = "The difference between approved and non-approved navigation devices."
r3 = "Common failure modes of flight and navigation instruments."
r4 = "The limitations of electronic flight bags."
r5 = "Failure to ensure currency of navigation databases."

[skills]
s1 = "Operate and manage installed instruments and navigation equipment."
