[meta]
letter = "B"
objective = "To determine the applicant exhibits satisfactory knowledge, risk management, and skills associated with IFR departure, en route, and arrival operations solely by reference to instruments."
name = "Departure, En Route, and Arrival Operations"
references = [
    "14 CFR parts 61",
    "91",
    "FAA-H-8083-15",
    "FAA-H-8083-16",
    "AC 91-74",
    "AFM",
    "AIM",
]

[knowledge]
1 = "Elements related to ATC routes, including departure procedures (DPs) and associated climb gradients; arrival procedures (STARs) and associated constraints."
2 = "Pilot/controller responsibilities, communication procedures, and ATC services available to pilots."

[risk_management]
1 = "Failure to communicate with ATC or follow published procedures."
2 = "Failure to recognize limitations of traffic avoidance equipment."
3 = "Failure to use see and avoid techniques when possible."

[skills]
1 = "Select, identify (as necessary) and use the appropriate communication and navigation facilities associated with the proposed flight."
2 = "Perform the appropriate airplane checklist items relative to the phase of flight."
3 = "Use the current and appropriate paper or electronic navigation publications.."
4 = "Establish two-way communications with the proper controlling agency, use proper phraseology, and comply in a timely manner with all ATC instructions and airspace restrictions, and exhibit adequate knowledge of communication failure procedures."
5 = "Intercept all courses, radials, and bearings appropriate to the procedure, route, or clearance in a timely manner."
6 = "Comply with all applicable charted procedures."
7 = "Maintain airspeed ±10 knots, altitude ±100 feet, and selected headings ±10°, and apply proper correction to maintain a course allowing no more than ¾-scale deflection of the CDI."
8 = "Update/interpret weather in flight."
9 = "Explain and use flight deck displays of digital weather and aeronautical information, as applicable."
10 = "Demonstrate SRM."
