[meta]
letter = "A"
objective = "To determine the applicant exhibits satisfactory knowledge, risk management, and skills associated with checking flight instruments and equipment during postflight."
name = "Checking Instruments and Equipment"
references = [
    "14 CFR parts 61, 91",
]

[meta.section]
name = "Postflight Procedures"
numeral = "VIII"

[knowledge]
1 = "Procedures for checking the functionality of all installed instruments and navigation equipment."

[risk_management]
1 = "Failure to perform a proper postflight inspection and properly document airplane discrepancies."

[skills]
1 = "Conduct a postflight inspection, and document discrepancies and servicing requirements, if any."
