[meta]
references = [
    "14 CFR parts 61",
    "91",
    "FAA-H-8083-15",
    "AIM",
]
objective = "To determine the applicant exhibits satisfactory knowledge, risk management, and skills associated with performing the procedures for a landing from an instrument approach."

[knowledge]
k1 = "Elements related to the pilot’s responsibilities, and the environmental, operational, and meteorological factors that affect landing from a straight-in or circling approach."
k2 = "Airport signs, markings and lighting, to include approach lighting systems."

[risk_management]
r1 = "Attempting to land from an unstable approach."
r2 = "Flying below the glidepath."
r3 = "Transitioning from instrument to visual references for landing."

[skills]
s1 = "Transition at the DA/DH, MDA, or visual descent point (VDP) to a visual flight condition, allowing for safe visual maneuvering and a normal landing."
s2 = "Adhere to all ATC or evaluator advisories, such as NOTAMs, windshear, wake turbulence, runway surface, braking conditions, and other operational considerations."
s3 = "Complete the appropriate checklist."
s4 = "Maintain positive airplane control throughout the landing maneuver."
s5 = "Demonstrate SRM."
