[meta]
letter = "C"
objective = "To determine the applicant exhibits satisfactory knowledge, risk management, and skills associated with performing a missed approach procedure solely by reference to instruments."
name = "Missed Approach"
references = [
    "14 CFR parts 61",
    "91",
    "FAA-H-8083-15",
    "IFP",
    "AIM",
]

[meta.section]
name = "Instrument Approach Procedures"
numeral = "VI"

[knowledge]
1 = "Elements related to missed approach procedures and limitations associated with standard instrument approaches, including while using an FMS or autopilot, if equipped."

[risk_management]
1 = "Failure to follow prescribed procedures."
2 = "Holding, diverting, or electing to fly the approach again."
3 = "Failure to ensure proper airplane configuration during an approach and missed approach."
4 = "Factors that might lead to executing a missed approach procedure before the missed approach point or to a go-around below DA/MDA."
5 = "Failure to manage automated navigation and autoflight systems."

[skills]
1 = "Promptly initiate the missed approach procedure and report it to ATC."
2 = "Apply the appropriate power setting for the flight condition and establish a pitch attitude necessary to obtain the desired performance."
3 = "Configure the airplane in accordance with airplane manufacturer’s instructions, establish a positive rate of climb, and accelerate to the appropriate airspeed, ±10 knots."
4 = "Follow the recommended checklist items appropriate to the missed approach/go-around procedure."
5 = "Comply with the published or alternate missed approach procedure."
6 = "Advise ATC or the evaluator if unable to comply with a clearance, restriction, or climb gradient."
7 = "Maintain the heading, course, or bearing ±10°; and altitude(s) ±100 feet during the missed approach procedure."
8 = "Use an MFD and other graphical navigation displays, if installed, to monitor position and track to help navigate the missed approach."
9 = "Demonstrate SRM or CRM, as appropriate."
10 = "Request ATC clearance to attempt another approach, proceed to the alternate airport, holding fix, or other clearance limit, as appropriate, or as directed by the evaluator."
