[meta]
references = [
    "14 CFR parts 61",
    "91",
    "FAA-H-8083-15",
    "FAA-H-8083-16",
    "IFP",
    "AIM",
    "AC 120-108",
]
objective = "To determine the applicant exhibits satisfactory knowledge, risk management, and skills associated with performing nonprecision approach procedures solely by reference to instruments."

[knowledge]
k1 = "Procedures and limitations associated with a nonprecision approach, including the differences between Localizer Performance (LP) and Lateral Navigation (LNAV) approach guidance."
k2 = "Navigation system annunciations expected during an RNAV approach."
k3 = "Ground-based and satellite-based navigation systems used for a nonprecision approach."
k4 = "A stabilized approach, to include energy management concepts."

[risk_management]
r1 = "Failure to follow the correct approach procedure (e.g., descending too early, etc.)."
r2 = "Selecting an incorrect navigation frequency."
r3 = "Failure to manage automated navigation and autoflight systems."
r4 = "Failure to ensure proper airplane configuration during an approach and missed approach."
r5 = "An unstable approach, including excessive descent rates."
r6 = "Deteriorating weather conditions on approach."
r7 = "Operating below the minimum descent altitude (MDA) or continuing a descent below decision altitude (DA) without proper visual references."

[skills]
s1 = "Accomplish the nonprecision instrument approaches selected by the evaluator."
s2 = "Establish two-way communications with ATC appropriate for the phase of flight or approach segment, and use proper communication phraseology."
s3 = "Select, tune, identify, and confirm the operational status of navigation equipment to be used for the approach."
s4 = "Comply with all clearances issued by ATC or the evaluator."
s5 = "Recognize if any flight instrumentation is inaccurate or inoperative, and take appropriate action."
s6 = "Advise ATC or the evaluator if unable to comply with a clearance."
s7 = "Complete the appropriate checklist."
s8 = "Establish the appropriate airplane configuration and airspeed considering meteorological and operating conditions."
s9 = "Maintain altitude ±100 feet, selected heading ±10°, airspeed ±10 knots, and accurately track radials, courses, and bearings, prior to beginning the final approach segment."
s10 = "Adjust the published MDA and visibility criteria for the aircraft approach category, as appropriate, for factors that include NOTAMs, inoperative aircraft or navigation equipment, or inoperative visual aids associated with the landing environment, etc."
s11 = "Establish a stabilized descent to the appropriate altitude."
s12 = "For the final approach segment, maintain no more than a ¾-scale deflection of the CDI, maintain airspeed ±10 knots, and altitude, if applicable, above MDA, +100/-0 feet, to the Visual Descent Point (VDP) or Missed Approach Point (MAP)."
s13 = "Execute the missed approach procedure if the required visual references are not distinctly visible and identifiable at the appropriate point or altitude for the approach profile; or execute a normal landing from a straight-in or circling approach."
s14 = "Use an MFD and other graphical navigation displays, if installed, to monitor position, track wind drift, and to maintain situational awareness."
