[meta]
letter = "E"
objective = "To determine the applicant exhibits satisfactory knowledge, risk management, and skills associated with performing the procedures for a landing from an instrument approach."
name = "Landing from an Instrument Approach"
references = [
    "14 CFR parts 61",
    "91",
    "FAA-H-8083-15",
    "AIM",
]

[meta.section]
name = "Instrument Approach Procedures"
numeral = "VI"

[knowledge]
1 = "Elements related to the pilot’s responsibilities, and the environmental, operational, and meteorological factors that affect landing from a straight-in or circling approach."
2 = "Airport signs, markings and lighting, to include approach lighting systems."

[risk_management]
1 = "Attempting to land from an unstable approach."
2 = "Flying below the glidepath."
3 = "Transitioning from instrument to visual references for landing."

[skills]
1 = "Transition at the DA/DH, MDA, or visual descent point (VDP) to a visual flight condition, allowing for safe visual maneuvering and a normal landing."
2 = "Adhere to all ATC or evaluator advisories, such as NOTAMs, windshear, wake turbulence, runway surface, braking conditions, and other operational considerations."
3 = "Complete the appropriate checklist."
4 = "Maintain positive airplane control throughout the landing maneuver."
5 = "Demonstrate SRM."
