[meta]
letter = "B"
objective = "To determine the applicant exhibits satisfactory knowledge, risk management and skills associated with flight solely by reference to instruments with one engine inoperative."
name = "One Engine Inoperative (Simulated) during Straight-and-Level Flight and Turns (AMEL, AMES)"
references = [
    "14 CFR 61",
    "FAA-H-8083-3",
    "FAA-H-8083-15",
]

[knowledge]
k1 = "Procedures used if engine failure occurs during straight-and-level flight and turns while on instruments."

[risk_management]
r1 = "Failure to identify the inoperative engine."
r2 = "Inability to climb or maintain altitude with an inoperative engine."
r3 = "Low altitude maneuvering including stall, spin, or CFIT."
r4 = "Distractions, loss of situational awareness, or improper task management."
r5 = "Fuel management during single-engine operation."

[skills]
s1 = "Promptly recognize an engine failure and maintain positive airplane control."
s2 = "Set the engine controls, reduce drag, identify and verify the inoperative engine, and simulate feathering of the propeller on the inoperative engine. (Evaluator should then establish zero thrust on the inoperative engine.)"
s3 = "Establish the best engine-inoperative airspeed and trim the airplane."
s4 = "Use flight controls in the proper combination as recommended by the manufacturer, or as required to maintain best performance, and trim as required."
s5 = "Verify the prescribed checklist procedures normally used for securing the inoperative engine."
s6 = "Attempt to determine and resolve the reason for the engine failure."
s7 = "Monitor engine functions and make necessary adjustments."
s8 = "Maintain the specified altitude ±100 feet or minimum sink rate if applicable, airspeed ±10 knots, and the specified heading ±10°."
s9 = "Assess the airplane’s performance capability and decide an appropriate action to ensure a safe landing."
s10 = "Avoid loss of airplane control or attempted flight contrary to the engine-inoperative operating limitations of the airplane."
s11 = "Demonstrate SRM."
