[meta]
letter = "C"
objective = "To determine that the applicant exhibits satisfactory knowledge, risk management, and skills associated with executing a published instrument approach solely by reference to instruments with one engine inoperative."
name = "Instrument Approach and Landing with an Inoperative Engine (Simulated) (AMEL, AMES)"
references = [
    "14 CFR parts 61,91",
    "FAA-H-8083-3",
    "FAA-H-8083-15",
    "IFP",
]

[knowledge]
1 = "Instrument approach procedures with one engine inoperative."

[risk_management]
1 = "Failure to plan for engine failure during approach and landing."
2 = "Collision hazards, to include aircraft, terrain, obstacles, wires, vehicles, vessels, persons, and wildlife."
3 = "Improper airplane configuration."
4 = "Low altitude maneuvering including stall, spin, or CFIT."
5 = "Distractions, loss of situational awareness, or improper task management."
6 = "Performing a go-around/rejected landing with a powerplant failure."

[skills]
1 = "Promptly recognize a engine failure and maintain positive airplane control."
2 = "Set the engine controls, reduce drag, identify and verify the inoperative engine, and simulate feathering of the propeller on the inoperative engine. (Evaluator should then establish zero thrust on the inoperative engine.)"
3 = "Use flight controls in the proper combination as recommended by the manufacturer, or as required to maintain best performance, and trim as required."
4 = "Follow the manufacturer’s recommended emergency procedures."
5 = "Monitor the operating engine and make adjustments as necessary."
6 = "Request and follow an actual or a simulated ATC clearance for an instrument approach."
7 = "Maintain altitude ±100 feet or minimum sink rate if applicable, airspeed ±10 knots, and selected heading ±10°."
8 = "Establish a rate of descent that will ensure arrival at the MDA or DA/DH with the airplane in a position from which a descent to a landing on the intended runway can be made, either straight in or circling as appropriate."
9 = "On final approach segment, maintain vertical (as applicable) and lateral guidance within ¾-scale deflection."
10 = "Avoid loss of airplane control, or attempted flight contrary to the operating limitations of the airplane."
11 = "Comply with the published criteria for the aircraft approach category if circling."
12 = "Execute a normal landing."
13 = "Complete the appropriate checklist."
