[meta]
letter = "D"
objective = "To determine the applicant exhibits satisfactory knowledge, risk management, and skills associated with performing an approach solely by reference to instruments with the loss of primary flight control instruments."
name = "Approach with Loss of Primary Flight Instrument Indicators"
references = [
    "14 CFR parts 61",
    "91",
    "FAA-H-8083-15",
    "IFP",
]

[meta.section]
name = "Emergency Operations"
numeral = "VII"

[knowledge]
1 = "Recognizing if primary flight instruments are inaccurate or inoperative, and advising ATC or the evaluator."
2 = "Common failure modes of vacuum and electric attitude instruments and how to correct or minimize the effect of their loss."

[risk_management]
1 = "Use of secondary flight displays when primary displays have failed."
2 = "Failure to maintain airplane control."
3 = "Distractions, loss of situational awareness, or improper task management."

[skills]
1 = "Advise ATC or the evaluator of if unable to comply with a clearance."
2 = "Complete a nonprecision instrument approach without the use of the primary flight instruments using the skill elements of the nonprecision approach Task (See Area of Operation VI, Task A)."
3 = "Demonstrate SRM."
